services:
  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: acc@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=users
    ports:
      - '5432:5432'

  mysql:
    container_name: database
    image: mysql:latest
    ports:
      - "32001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: employees
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    profiles: [ app, full ]
  backend:
    container_name: api
    links:
      - "mysql"
    build: .
    expose:
      - "8000"
    ports:
      - "8000:8000"
    restart: "always"
    profiles: [ app, full ]

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    ports:
      - "3000:3000"
    restart: "always"
    profiles: [ full ]
