services:
  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: acc@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
  dev_db:
    container_name: dev_db
    build:
      context: ./
      dockerfile: Dockerfile.sql
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=users
    ports:
      - '5432:5432'
    profiles: [ dev ]

  test_db:
    container_name: test_db
    build:
      context: ./
      dockerfile: Dockerfile.sql
    restart: unless-stopped
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - '5432:5432'
    profiles: [ test ]

  docker_db:
    container_name: database
    build:
      context: ./
      dockerfile: Dockerfile.sql
    restart: unless-stopped
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    ports:
      - '5432:5432'
    profiles: [ app, full ]

  backend:
    container_name: api
    build: .
    expose:
      - "8000"
    ports:
      - "8000:8000"
    restart: "always"
    profiles: [ app, full ]

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
    restart: "always"
    profiles: [ full ]
