name: Backend styling

on: [push]

jobs:
  styling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          python-version: 3.12
      - name: Install pipenv
        run: pip install pipenv
      - name: Pipenv version
        run: pipenv --version
      - name: Check Pipfile content
        working-directory: ./backend
        run: cat Pipfile
      - name: Run lint
        working-directory: ./backend
        run: pipenv run check