name: Backend styling

on: [push]

jobs:
  styling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Navigate to directory
        run: cd ..backend
      - name: List elements
        run: ls
      - name: Lint Python
        uses: actions/checkout@v4
        with:
          python-version: 3.12
      - name: Install pipenv
        run: pip install pipenv
      - name: Pipenv version
        run: pipenv --version
      - name: Check Pipfile content
        run: cat Pipfile
      - name: Run lint
        run: pipenv run check