name: Backend styling

on: [push]

jobs:
  styling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          python-version: 3.12
      - name: Run lint
        working-directory: ./backend/tools
        run: bash lint_check.sh